/**
 * AI_CONTEXT: Shared de/en copy dictionary for the videos workspace — VideosView
 * and its extracted subcomponents (VideoStudyBar, VideoDownloadControl,
 * ChapterDownloadButton) all key off the same Copy type.
 */
export const COPY = {
  de: {
    title: 'Lernvideos',
    subtitle: 'Professor Messer · CompTIA Security+ SY0-701 · lokal',
    back: 'Zurück',
    close: 'Schließen',
    courseIndex: 'Kompletter Kursindex (YouTube)',
    objective: 'Objective',
    seen: 'GESEHEN',
    open: 'OFFEN',
    pickVideo: 'Wähle links ein Video aus, um es hier abzuspielen.',
    hasNote: 'Notiz vorhanden',
    recall: 'Abruf-Check',
    transcript: 'Transkript',
    verdictUnderstood: 'VERSTANDEN',
    verdictAlmost: 'FAST',
    verdictReview: 'NOCHMAL',
    confidenceLabel: 'Selbsteinschätzung',
    confidenceHint: 'Schau das Video, prüf dich aktiv und setz ehrlich deinen Status — Schauen allein ist noch kein Können.',
    deckRate: 'Deck-Quote: {rate} % ({total} Reviews)',
    calibrationWarning: 'Deine Einschätzung liegt über der tatsächlichen Quote — prüf dich noch mal aktiv.',
    gaps: 'LÜCKEN',
    ok: 'OKAY',
    solid: 'SICHER',
    gapsFull: 'Lücken',
    okFull: 'Okay',
    solidFull: 'Sicher',
    loading: 'Lade Videoliste …',
    unreachableTitle: 'Server nicht erreichbar',
    unreachableHint: 'Ohne Verbindung zum Pi sind nur heruntergeladene Videos verfügbar.',
    noVideos: 'Keine lokalen Videos gefunden.',
    download: 'Offline speichern',
    downloading: 'Lädt',
    offline: 'Offline',
    removeDownload: 'Offline-Kopie entfernen',
    allOffline: 'Alle offline',
    streamOnly: 'Nur online (nicht heruntergeladen)',
    resolving: 'Offline-Kopie wird geladen …',
    storage: '{count} offline · {size}',
    chapterDownload: 'Kapitel laden',
    cancel: 'Abbrechen',
    chapterOffline: 'Kapitel offline',
    queued: 'Wartet',
    quotaError: 'Gerätespeicher voll — nicht alle Videos konnten offline gesichert werden.',
    fullscreen: 'Vollbild',
    exitFullscreen: 'Vollbild verlassen',
    speed: 'Geschwindigkeit',
    noteStats: '{notes} Zettel · {tags} Tags',
    tags: 'Tags',
    course: 'Kurs',
    showCourse: 'Kurs öffnen',
    hideCourse: 'Kurs schließen',
    collapseRecall: 'Abruf-Check einklappen',
    done: 'Fertig',
    backToVideo: 'Video',
  },
  en: {
    title: 'Videos',
    subtitle: 'Professor Messer · CompTIA Security+ SY0-701 · local',
    back: 'Back',
    close: 'Close',
    courseIndex: 'Full course index (YouTube)',
    objective: 'Objective',
    seen: 'SEEN',
    open: 'OPEN',
    pickVideo: 'Pick a video on the left to play it here.',
    hasNote: 'Has note',
    recall: 'Recall check',
    transcript: 'Transcript',
    verdictUnderstood: 'GOT IT',
    verdictAlmost: 'ALMOST',
    verdictReview: 'REVIEW',
    confidenceLabel: 'Self-assessment',
    confidenceHint: 'Watch the video, quiz yourself, and set your status honestly — watching alone is not knowing.',
    deckRate: 'Deck rate: {rate}% ({total} reviews)',
    calibrationWarning: 'Your self-assessment is above your actual rate — quiz yourself again.',
    gaps: 'GAPS',
    ok: 'OKAY',
    solid: 'SOLID',
    gapsFull: 'Gaps',
    okFull: 'Okay',
    solidFull: 'Solid',
    loading: 'Loading video list …',
    unreachableTitle: 'Server unreachable',
    unreachableHint: 'Without a connection to the Pi, only downloaded videos are available.',
    noVideos: 'No local videos found.',
    download: 'Save offline',
    downloading: 'Loading',
    offline: 'Offline',
    removeDownload: 'Remove offline copy',
    allOffline: 'All offline',
    streamOnly: 'Online only (not downloaded)',
    resolving: 'Loading offline copy …',
    storage: '{count} offline · {size}',
    chapterDownload: 'Download chapter',
    cancel: 'Cancel',
    chapterOffline: 'Chapter offline',
    queued: 'Queued',
    quotaError: 'Device storage full — not all videos could be saved offline.',
    fullscreen: 'Fullscreen',
    exitFullscreen: 'Exit fullscreen',
    speed: 'Playback speed',
    noteStats: '{notes} notes · {tags} tags',
    tags: 'Tags',
    course: 'Course',
    showCourse: 'Open course',
    hideCourse: 'Close course',
    collapseRecall: 'Collapse recall',
    done: 'Done',
    backToVideo: 'Video',
  },
} as const

export type Copy = (typeof COPY)[keyof typeof COPY]
