/**
 * AI_CONTEXT:
 * Role: Lazy loader for the per-video Messer transcript assets (public/messer-transcripts/NNN.json).
 * Used by: VideoTranscriptPanel (read-along transcript for the active video).
 * Important: Assets are generated by scripts/build-messer-transcripts.mjs; a missing file is a normal state, not an error.
 */
import { useEffect, useState } from 'react'

export interface MesserVideoTranscript {
  /** 3-stelliger Playlist-Index ("031"). */
  index: string
  objective: string | null
  title: string
  /** Redaktionelle Transkript-Absätze (professormesser.com), in Videoreihenfolge. */
  paragraphs: string[]
}

export type TranscriptStatus = 'idle' | 'loading' | 'ready' | 'missing'

/** Einmal geladene Transkripte für die Session behalten (~10 KB je Video). */
const transcriptCache = new Map<number, MesserVideoTranscript | null>()

function transcriptUrl(index: number): string {
  return `/messer-transcripts/${String(index).padStart(3, '0')}.json`
}

/** Holt das Transkript eines Videos vom Server (SW cached es für offline nach). */
export async function fetchMesserVideoTranscript(index: number): Promise<MesserVideoTranscript | null> {
  if (transcriptCache.has(index)) return transcriptCache.get(index) ?? null
  try {
    const response = await fetch(transcriptUrl(index))
    if (!response.ok) {
      transcriptCache.set(index, null)
      return null
    }
    const data = (await response.json()) as MesserVideoTranscript
    const valid = Array.isArray(data?.paragraphs) && data.paragraphs.every(p => typeof p === 'string')
    const transcript = valid ? data : null
    transcriptCache.set(index, transcript)
    return transcript
  } catch {
    // Netzfehler nicht negativ cachen — beim nächsten Öffnen erneut versuchen.
    return null
  }
}

export function useMesserVideoTranscript(index: number | null) {
  const [status, setStatus] = useState<TranscriptStatus>('idle')
  const [transcript, setTranscript] = useState<MesserVideoTranscript | null>(null)

  useEffect(() => {
    if (index === null) {
      setStatus('idle')
      setTranscript(null)
      return
    }
    let cancelled = false
    setStatus('loading')
    setTranscript(null)
    void fetchMesserVideoTranscript(index).then(result => {
      if (cancelled) return
      setTranscript(result)
      setStatus(result ? 'ready' : 'missing')
    })
    return () => {
      cancelled = true
    }
  }, [index])

  return { status, transcript }
}
